version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: es01
    ports: 
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    environment: 
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: password
  kibana: 
    image: docker.elastic.co/kibana/kibana:8.1.2
    container_name: kib01
    ports: 
      - "5601:5601"
    networks: 
      - elastic
    depends_on:
      - elasticsearch
networks: 
  elastic: 
    driver: bridge